version: "3.3"

services:
  ocaservice:
    image: amikom/ocaservice:1.0.0
    container_name: ocaservice
    restart: always
    env_file:
      - .env
    environment:
      TZ: "Asia/Jakarta"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4018:3000

# networks:
#   default:
#     external: true
#     name: docker_network